# -*- coding: utf-8 -*-

"""
   uberapilib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
"""
from .api_helper import APIHelper

class Configuration(object):

    """A class used for configuring the SDK by a user.
    
    This class need not be instantiated and all properties and methods
	are accessible without instance creation.
    
    """

    # The base Uri for API calls
    base_uri = 'https://api.uber.com/v1'

    # The username to use with basic authentication
    # TODO: Set an appropriate value
    basic_auth_user_name = "TODO: Replace"

    # The password to use with basic authentication
    # TODO: Set an appropriate value
    basic_auth_password = "TODO: Replace"


