# -*- coding: utf-8 -*-

"""
    uberapilib.uber_api_client

    This file was automatically generated by APIMATIC BETA v2.0 on 12/13/2016
"""

from .http import *
from .models import *
from .exceptions import *
from .decorators import *
from .controllers import *

class UberAPIClient(object):

    @lazy_property
    def client(self):
        return APIController()


    def __init__(self, 
                 basic_auth_user_name = None,
                 basic_auth_password = None):
        if basic_auth_user_name != None:
            Configuration.basic_auth_user_name = basic_auth_user_name
        if basic_auth_password != None:
            Configuration.basic_auth_password = basic_auth_password


