# -*- coding: utf-8 -*-

"""
    uberapilib.models.promotions_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
"""
from .base_model import BaseModel

class PromotionsResponse(BaseModel):

    """Implementation of the 'Promotions Response' model.

    Information about promotions

    Attributes:
        display_text (string): A localized string we recommend to use when
            offering the promotion to users.
        localized_value (string): The value of the promotion that is available
            to a user in this location in the local currency.
        mtype (string): The type of the promo which is either "trip_credit" or
            "account_credit".

    """

    def __init__(self, 
                 display_text = None,
                 localized_value = None,
                 mtype = None):
        """Constructor for the PromotionsResponse class"""
        
        # Initialize members of the class
        self.display_text = display_text
        self.localized_value = localized_value
        self.mtype = mtype

        # Create a mapping from Model property names to API property names
        self.names = {
            "display_text" : "display_text",
            "localized_value" : "localized_value",
            "mtype" : "type",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            display_text = dictionary.get("display_text")
            localized_value = dictionary.get("localized_value")
            mtype = dictionary.get("type")
            # Return an object of this model
            return cls(display_text,
                       localized_value,
                       mtype)
