# -*- coding: utf-8 -*-

"""
    uberapilib.models.request_map_response
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
"""
from .base_model import BaseModel

class RequestMapResponse(BaseModel):

    """Implementation of the 'Request Map Response' model.

    Request Map Response

    Attributes:
        href (string): TODO: type description here.
        request_id (string): TODO: type description here.

    """

    def __init__(self, 
                 href = None,
                 request_id = None):
        """Constructor for the RequestMapResponse class"""
        
        # Initialize members of the class
        self.href = href
        self.request_id = request_id

        # Create a mapping from Model property names to API property names
        self.names = {
            "href" : "href",
            "request_id" : "request_id",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            href = dictionary.get("href")
            request_id = dictionary.get("request_id")
            # Return an object of this model
            return cls(href,
                       request_id)
