# -*- coding: utf-8 -*-

"""
    uberapilib.models.surge_confirmation
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
"""
from .base_model import BaseModel

class SurgeConfirmation(BaseModel):

    """Implementation of the 'surge_confirmation' model.

    TODO: type model description here.

    Attributes:
        href (string): TODO: type description here.
        surge_confirmation_id (string): TODO: type description here.

    """

    def __init__(self, 
                 href = None,
                 surge_confirmation_id = None):
        """Constructor for the SurgeConfirmation class"""
        
        # Initialize members of the class
        self.href = href
        self.surge_confirmation_id = surge_confirmation_id

        # Create a mapping from Model property names to API property names
        self.names = {
            "href" : "href",
            "surge_confirmation_id" : "surge_confirmation_id",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            href = dictionary.get("href")
            surge_confirmation_id = dictionary.get("surge_confirmation_id")
            # Return an object of this model
            return cls(href,
                       surge_confirmation_id)
