# -*- coding: utf-8 -*-

"""
    uberapilib.models.time_estimate
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 12/13/2016
"""
from .base_model import BaseModel

class TimeEstimate(BaseModel):

    """Implementation of the 'Time Estimate' model.

    Time estimates e.g., ETA

    Attributes:
        display_name (string): Display name of product.
        estimate (int): ETA for the product (in seconds). Always show estimate
            in minutes.
        product_id (string): Unique identifier representing a specific product
            for a given latitude & longitude. For example, uberX in San
            Francisco will have a different product_id than uberX in Los
            Angeles.

    """

    def __init__(self, 
                 display_name = None,
                 estimate = None,
                 product_id = None):
        """Constructor for the TimeEstimate class"""
        
        # Initialize members of the class
        self.display_name = display_name
        self.estimate = estimate
        self.product_id = product_id

        # Create a mapping from Model property names to API property names
        self.names = {
            "display_name" : "display_name",
            "estimate" : "estimate",
            "product_id" : "product_id",
        }


    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """
        if dictionary == None:
            return None
        else:
            # Extract variables from the dictionary
            display_name = dictionary.get("display_name")
            estimate = dictionary.get("estimate")
            product_id = dictionary.get("product_id")
            # Return an object of this model
            return cls(display_name,
                       estimate,
                       product_id)
